version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cadastro-backend
    environment:
      DATABASE_URL: postgresql://admin:Salcifufu@0412@10.0.0.13:5432/teste
      DEBUG: false
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    networks:
      - cadastro-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cadastro-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    networks:
      - cadastro-network

networks:
  cadastro-network:
    driver: bridge
